# Generated by Django 4.2.7 on 2024-09-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0002_pet_vaccinations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='petvaccination',
            unique_together={('pet', 'vaccination')},
        ),
    ]
